on:
  push:
  pull_request:
jobs:
  compile_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - run: arduino-cli version
      - name: Compile sketch
        run: arduino-cli compile --profile controllino_micro --verbose
      - name: Lint sketch
        uses: arduino/arduino-lint-action@v3
